INSERT INTO DP_USER VALUES ( CURRENT_TIMESTAMP() ,1, 'Ahmed', 'EMPLOYEE');
INSERT INTO DP_USER VALUES ( CURRENT_TIMESTAMP() ,2, 'John', 'AFFILIATE');
INSERT INTO DP_USER VALUES ( CURRENT_TIMESTAMP() ,3, 'Jackson', 'LOYAL_CUSTOMER');
INSERT INTO DP_USER VALUES ( CURRENT_TIMESTAMP() ,4, 'Samia', 'CUSTOMER');